import { WortZwillingScreen, ZeitenwendeScreen, LueckenfuellerScreen } from '../components/AppLazyScreens'

export function useGameScreenProps({
  phase,
  thema,
  themaKurz,
  themaQuelle,
  lemmata,
  playedIds,
  selectedLemma,
  handleRoundComplete,
  roundScores,
  wortzwilling,
  wzPlayed,
  zeitenwende,
  zwPlayed,
  lueckenfuellerLemma,
  lfPlayed,
  spezialwoche,
  swWzPlayed,
  swZwPlayed,
  swLfPlayed,
  handleWZFinish,
  handleZeitenwendeFinish,
  handleLFFinish,
  handleSwWZFinish,
  handleSwZeitenwendeFinish,
  handleSwLFFinish,
  gameScreenActions,
  tabState,
  gesamtausgabe,
  customLemmaQuota,
  onCustomPlay,
  customGame,
  onExitCustomGame,
  serverDatum,
}) {
  return {
    phase,
    thema,
    themaKurz,
    themaQuelle,
    lemmata,
    playedIds,
    serverDatum,
    gesamtausgabe,
    customLemmaQuota,
    onCustomPlay,
    customGame,
    onExitCustomGame,
    handleLemmaSelect: gameScreenActions.onLemmaSelect,
    handleViewResult: gameScreenActions.onViewResult,
    onBackToHome: gameScreenActions.onBackToHome,
    selectedLemma,
    handleRoundComplete,
    onBackToSelection: gameScreenActions.onBackToSelection,
    roundScores,
    handleRestart: gameScreenActions.onRestart,
    wortzwilling,
    onWortzwillingBack: gameScreenActions.onWortzwillingBack,
    onWortzwillingSelectionBack: gameScreenActions.onWortzwillingSelectionBack,
    onWortzwillingPlay: tabState.goToWortzwillingGame,
    onWortzwillingViewResult: tabState.viewWortzwillingResult,
    handleWZFinish,
    wzViewOnly: tabState.wzViewOnly,
    wzPlayed,
    WortZwilling: WortZwillingScreen,
    zeitenwende,
    onZeitenwendeBack: gameScreenActions.onZeitenwendeBack,
    onZeitenwendeSelectionBack: gameScreenActions.onZeitenwendeSelectionBack,
    onZeitenwendePlay: tabState.goToZeitenwendeGame,
    onZeitenwendeViewResult: tabState.viewZeitenwendeResult,
    handleZeitenwendeFinish,
    zwViewOnly: tabState.zwViewOnly,
    zwPlayed,
    zwProgress: gameScreenActions.zwProgress,
    Zeitenwende: ZeitenwendeScreen,
    lueckenfuellerLemma,
    onLueckenfuellerSelectionBack: gameScreenActions.onLueckenfuellerSelectionBack,
    onLueckenfuellerPlay: tabState.goToLueckenfuellerGame,
    onLueckenfuellerViewResult: tabState.viewLueckenfuellerResult,
    onLueckenfuellerBack: gameScreenActions.onLueckenfuellerBack,
    handleLFFinish,
    lfViewOnly: tabState.lfViewOnly,
    lfPlayed,
    lfProgress: gameScreenActions.lfProgress,
    Lueckenfueller: LueckenfuellerScreen,
    spezialwoche,
    swWzPlayed,
    swZwPlayed,
    swLfPlayed,
    handleSwWZFinish,
    handleSwZeitenwendeFinish,
    handleSwLFFinish,
    swWzViewOnly: tabState.swWzViewOnly,
    swZwViewOnly: tabState.swZwViewOnly,
    swLfViewOnly: tabState.swLfViewOnly,
    onSwWzPlay: tabState.goToSwWzGame,
    onSwZwPlay: tabState.goToSwZeitenwendeGame,
    onSwLfPlay: tabState.goToSwLfGame,
    onViewSwWz: tabState.viewSwWz,
    onViewSwZw: tabState.viewSwZw,
    onViewSwLf: tabState.viewSwLf,
    onSwBack: gameScreenActions.onBackToHome,
  }
}
